/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AUTH_API_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AWS_SES_ACCESS_KEY_ID": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AWS_SES_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AuthApi": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AuthStorage": {
      "namespaceId": string
      "type": "sst.cloudflare.Kv"
    }
    "CLAUDIO_MANAGED_TIERS": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "CLAUDIO_MINIMAX_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Console": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "EMAILOCTOPUS_API_KEY": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "GITHUB_CLIENT_ID_CONSOLE": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "GITHUB_CLIENT_SECRET_CONSOLE": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "GatewayKv": {
      "namespaceId": string
      "type": "sst.cloudflare.Kv"
    }
    "HONEYCOMB_API_KEY": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "LogProcessor": {
      "type": "sst.cloudflare.Worker"
    }
    "SALESFORCE_CLIENT_ID": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "SALESFORCE_CLIENT_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "SALESFORCE_INSTANCE_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "STRIPE_PUBLISHABLE_KEY": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_BLACK_PRICE": {
      "plan100": string
      "plan20": string
      "plan200": string
      "product": string
      "type": "sst.sst.Linkable"
    }
    "ZEN_LIMITS": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_LITE_PRICE": {
      "firstMonth50Coupon": string
      "price": string
      "priceInr": number
      "product": string
      "type": "sst.sst.Linkable"
    }
    "ZEN_MODELS1": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS10": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS11": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS12": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS13": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS14": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS15": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS16": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS17": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS18": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS19": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS2": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS20": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS21": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS22": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS23": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS24": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS25": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS26": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS27": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS28": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS29": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS3": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS30": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS4": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS5": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS6": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS7": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS8": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_MODELS9": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_SESSION_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZenData": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "ZenDataNew": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}